// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtkcepqqglygqbqfjfbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0a2NlcHFxZ2x5Z3FicWZqZmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyMDEzMzUsImV4cCI6MjA5Mzc3NzMzNX0.a4LZfJEnDdEVOoooRt5PkkWHqR7Efi2U_-LkOgvpqbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});